baseURL = "https://edleeman.co.uk"
languageCode = "en-gb"
title = "Ed Leeman"
theme = "hugo-theme-mini"
hasCJKLanguage = true

[permalinks]
  posts = "/posts/:title/"

[social]
  twitter = "https://twitter.com/selfhostingblog"

[params]
  author = "Ed Leeman"
  bio = "Software Engineer | Platform Engineer | Privacy Advocate"
  description = "My corner of the internet where I try my best to write something that might be somewhat useful for someone else"
  enableRSS = true
  enableComments = true
  lastfmUsername = "ed1727"
  lastfmApiKey = "35d69c5ad21f4fc86e2d4269b9c949bd"

[markup]
  [markup.highlight]
    anchorLineNos = false
    codeFences = true
    guessSyntax = true
    hl_Lines = ""
    lineAnchors = ""
    lineNoStart = 1
    lineNos = true
    lineNumbersInTable = false
    noClasses = false
    style = "rose-pine-moon"
    tabWidth = 4
