baseURL = "https://edleeman.co.uk"
languageCode = "en-gb"
title = "Ed Leeman"
theme = "shibui"
hasCJKLanguage = true
buildFuture = true

[permalinks]
  posts = "/posts/:title/"

[params]
  description = "My corner of the internet where I try my best to write something that might be somewhat useful for someone else"
  author = "Ed Leeman"
  authorEmail = "ed@bowlerdesign.co.uk"
  bio = "Software Engineer | Platform Engineer | Privacy Advocate"
  lastfmUsername = "ed1727"
  lastfmApiKey = "35d69c5ad21f4fc86e2d4269b9c949bd"
  showreadingtime = false
  showlastmod = false
  toc = false

[[menu.main]]
  name = "about"
  url = "/about/"
  weight = 1

[[menu.main]]
  name = "posts"
  url = "/posts/"
  weight = 2

[[menu.main]]
  name = "notes"
  url = "/notes/"
  weight = 3

[[menu.main]]
  name = "projects"
  url = "/projects/"
  weight = 4

[[menu.main]]
  name = "/slashpages"
  url = "/slashpages/"
  weight = 5

[[menu.main]]
  name = "rss"
  url = "/rss/"
  weight = 6

[mediaTypes]
  [mediaTypes."text/x-opml"]
    suffixes = ["opml"]

[outputFormats]
  [outputFormats.OPML]
    mediaType = "text/x-opml"
    baseName = "blogroll"
    isPlainText = true
    notAlternative = true

[outputs]
  home = ["HTML", "RSS", "OPML"]

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
  [markup.highlight]
    anchorLineNos = false
    codeFences = true
    guessSyntax = true
    hl_Lines = ""
    lineAnchors = ""
    lineNoStart = 1
    lineNos = true
    lineNumbersInTable = false
    noClasses = false
    style = "rose-pine-moon"
    tabWidth = 4
