services:
  micropub:
    build: .
    environment:
      BEARER_TOKEN: "${BEARER_TOKEN}"
      REPO_PATH: /repo
      SITE_URL: https://edleeman.co.uk
    volumes:
      - /home/ed/docker-projects/edleeman.co.uk:/repo
      - /home/ed/.ssh:/root/.ssh:ro
    restart: unless-stopped
    networks:
      - traefik
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.micropub.rule=Host(`micropub.lan`)"
      - "traefik.http.routers.micropub.entrypoints=websecure"
      - "traefik.http.routers.micropub.tls=true"
      - "traefik.http.services.micropub.loadbalancer.server.port=3000"

networks:
  traefik:
    external: true
