services:
  micropub:
    build: .
    ports:
      - "3010:3000"
    environment:
      BEARER_TOKEN: "${BEARER_TOKEN}"
      REPO_PATH: /repo
      SITE_URL: https://edleeman.co.uk
    volumes:
      - /home/ed/docker-projects/edleeman.co.uk:/repo
      - /home/ed/.ssh:/root/.ssh:ro
    restart: unless-stopped
